interface types {
    //use jabratech:common/types.{pair, currency, option-kind, side, option-type, payout-ccy, instrument-kind, counterparty, user};

    /** 
     * Record representing an error result
     * - error-code: an error code for validation
     * - error-msg: description of error
     */
    record error {
      error-code: s16,
      error-msg: string
    }

    record get-balance-request {
      data: list<get-balance-request-data>
    }

    record get-balance-response {
      data: list<get-balance-response-data>
    }

    record get-balance-request-data {
      counterparty: string,
      sub-ledger: string
    }

    record get-balance-response-data {
      counterparty: string,
      sub-ledger: string,
      balances: list<balances>
    }

    record balances {
      currency: string,
      amount: f64
    }    
}